checks on user

diff --git a/os/sh/setup-user b/os/sh/setup-user
--- a/os/sh/setup-user
+++ b/os/sh/setup-user
@@ -1,3 +1,12 @@
+if [ "${USER}" = "root" ]; then
+  echo " $(tput bold)root$(tput sgr0) user $(tput smul)cannot$(tput rmul) setup the app"
+  exit 1
+fi
+if [ "$(which npm 2> /dev/null)" = "" ]; then
+  echo " please install $(tput bold)setup-system$(tput sgr0) first"
+  exit 1
+fi
+
 # setup ~/
 cd ~/
 touch .hushlogin
