sunxi-mali

diff --git a/os/sh/sunxi-mali b/os/sh/sunxi-mali
--- a/os/sh/sunxi-mali
+++ b/os/sh/sunxi-mali
@@ -12,6 +12,19 @@ fi
 
 sudo pacman -S --needed --noconfirm xorg-server-devel xorg-server mesa-libgl make gcc git automake autoconf pkg-config libtool sunxi-tools
 
+if [ ! -f /etc/default/cpupower ]; then
+  sudo pacman -S --needed --noconfirm cpupower
+  sync
+  sudo sh -c "echo 'governor=\"performance\"'>>/etc/default/cpupower"
+  sudo systemctl enable cpupower.service
+  sudo systemctl start cpupower.service
+fi
+
+if [[ $? -ne 0 ]] ; then
+  echo 'Unable to setup governor'
+  exit 1
+fi
+
 mkdir -p ~/.sunxi-mali
 cd ~/.sunxi-mali
 
