sunxi-mali

diff --git a/os/sh/sunxi-mali b/os/sh/sunxi-mali
--- a/os/sh/sunxi-mali
+++ b/os/sh/sunxi-mali
@@ -10,6 +10,17 @@ if [ ! -f /boot/script.bin ]; then
   exit 1
 fi
 
+sudo pacman -S --needed --noconfirm xorg-server-devel xorg-server mesa-libgl make gcc git automake autoconf pkg-config libtool sunxi-tools
+
+sudo bin2fex /boot/script.bin ~/.sunxi-mali/script.fex
+sudo sed -i 's/fb([0-9]*)_framebuffer_num = 2/fb\1_framebuffer_num = 3/g' ~/.sunxi-mali/script.fex
+sudo fex2bin ~/.sunxi-mali/script.fex /boot/script.bin
+
+if [[ $? -ne 0 ]] ; then
+  echo 'Unable to update script.bin'
+  exit 1
+fi
+
 sudo usermod -aG video $USER
 
 if [ ! -f /usr/lib/modules-load.d/modules.conf ]; then
@@ -23,7 +34,6 @@ mali_drm" >/usr/lib/modules-load.d/modules.conf'
   sudo modprobe mali_drm
 fi
 
-sudo pacman -S --needed --noconfirm xorg-server-devel xorg-server mesa-libgl make gcc git automake autoconf pkg-config libtool sunxi-tools
 mkdir -p ~/.sunxi-mali
 
 cd ~/.sunxi-mali
@@ -140,10 +150,7 @@ if [ ! -d ~/.sunxi-mali/libvdpau-sunxi ]; then
   subfont=/usr/share/fonts/TTF/DejaVuSans.ttf
   subcp=cp1250' > ~/.mplayer/config
 
-  sudo bin2fex /boot/script.bin ~/.sunxi-mali/script.fex
-  sudo sed -i 's/fb([0-9]*)_framebuffer_num = 2/fb\1_framebuffer_num = 3/g' ~/.sunxi-mali/script.fex
-  sudo fex2bin ~/.sunxi-mali/script.fex /boot/script.bin
-
-  cd ~/.sunxi-mali/sunxi-mali/test
-  cc -Wall -o test test.c -lEGL -lGLESv2 -lX11
 fi
+
+cd ~/.sunxi-mali/sunxi-mali/test
+cc -Wall -o test test.c -lEGL -lGLESv2 -lX11
